# Generated by Django 4.0 on 2021-12-30 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('topic', models.CharField(max_length=100)),
                ('likes', models.IntegerField(default=0)),
                ('image_url', models.URLField()),
                ('post_content', models.TextField()),
                ('author', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
