# Generated by Django 4.0 on 2021-12-30 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bookmarked_posts',
            field=models.ManyToManyField(blank=True, to='posts.Post'),
        ),
    ]
